run_dir: "ci-3-conda-rundir/"
start_date: "2016-01-01"
end_date: "2023-12-31"
run_LAI_date: "2016-07-01"
n_ens: 5
n_met: 3
n_ic: 20
n_event: 5
n_workers: 1
use_apptainer: false
pecan_parallelism_mode: slurm-sbatch
sbatch_additional_arguments: "-p node"
workflow_parallelism_mode: slurm-srun
srun_additional_arguments: "-p node --mem=0"
step_dispatch_configuration:
  convert-clim:
    slurm: true
    method: srun
    additional_arguments: "-p node --mem=0"
  build-ic:
    slurm: true
    method: srun
    additional_arguments: "-p node --mem=0"
  build-events:
    slurm: true
    method: srun
    additional_arguments: "-p node --mem=0"
  build-xml:
    slurm: true
    method: srun
    additional_arguments: "-p node --mem=0"
aws_profile: magic
external_paths:
  copy_to_rundir:
    template_file: "examples/3_rowcrop/template.xml"
    site_info_file: ".github/ci/site_info_3.csv"
  link_in_place: {}

paths:
  template_file: "examples/3_rowcrop/template.xml"
  site_info_file: ".github/ci/site_info_3.csv"
  phenology_info_path: "data_raw/management/phenology/v1.0/"
  planting_info_path: "data_raw/management/planting/v1.0/"
  harvest_info_path: "data_raw/management/harvest/v1.0/"
  tillage_info_path: "data_raw/management/tillage/v1.0/"
  irrigation_info_path: "data_raw/management/irrigation/v1.1/"
  fertilization_info_path: "data_raw/management/fertilization/v1.0/"
  ncc_info_path: "data_raw/management/ncc/v1.0/"
  site_era5_path: "data_raw/ERA5_CA_nc"
  landtrendr_agb_file: "data_raw/IC/landtrendr_2016_biomass_by_dwr_parcel.parquet"
